//Unused, just for example. This entity could be implemented to being
//stored in a db repo or another service for tracking users queries, metrics and marketing.

export class UserSearch {
  private _key: string;
  private _deviceId: string;
  private _created: Date; // maybe autogenerated by DB Engine.
  protected constructor(key: string, deviceId: string) {
    this._key = key;
    this._deviceId = deviceId;
  }
}
